baseURL = "https://deepthink.blog"
languageCode = "en-us"
title = "DeepThink.Blog"
theme="archie"
copyright = "© DeepThink.blog"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	favicon = "image/logo.png"
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Think what you think, do what you do."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
 
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/relaxcn"

# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "https://twitter.com/athulcajay/"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

